<?php
/** Run: php tests/seo-regression.php. This is not a live WordPress test. */
error_reporting( E_ALL );
set_error_handler( function ( $severity, $message, $file, $line ) { throw new ErrorException( $message, 0, $severity, $file, $line ); } );
define( 'ABSPATH', __DIR__ . '/' );
define( 'HOUR_IN_SECONDS', 3600 ); define( 'MINUTE_IN_SECONDS', 60 ); define( 'ARRAY_A', 'ARRAY_A' );
define( 'MAJESTIC_TUBE_DIR', dirname( __DIR__ ) ); define( 'MAJESTIC_TUBE_URI', 'https://example.test/theme' ); define( 'MAJESTIC_TUBE_VERSION', '2.2.26' );
$GLOBALS['hooks'] = array(); $GLOBALS['options'] = array( 'permalink_structure' => '/%postname%/' ); $GLOBALS['query_vars'] = array(); $GLOBALS['post_meta'] = array(); $GLOBALS['term_meta'] = array(); $GLOBALS['plugin'] = false; $GLOBALS['conditions'] = array(); $GLOBALS['allowed'] = true;
function add_filter( $tag, $callback, $priority = 10, $args = 1 ) { $GLOBALS['hooks'][ $tag ][ $priority ][] = array( $callback, $args ); }
function add_action( $tag, $callback, $priority = 10, $args = 1 ) { add_filter( $tag, $callback, $priority, $args ); }
function apply_filters( $tag, $value, ...$args ) { $hooks = $GLOBALS['hooks'][ $tag ] ?? array(); ksort( $hooks ); foreach ( $hooks as $callbacks ) { foreach ( $callbacks as $c ) { $value = call_user_func_array( $c[0], array_slice( array_merge( array( $value ), $args ), 0, $c[1] ) ); } } return $value; }
function __( $text, $domain = '' ) { return $text; } function _n( $one, $many, $count, $domain = '' ) { return 1 === $count ? $one : $many; }
function esc_html( $value ) { return htmlspecialchars( (string) $value, ENT_QUOTES, 'UTF-8' ); } function esc_attr( $value ) { return esc_html( $value ); } function esc_textarea( $value ) { return esc_html( $value ); } function esc_url( $value ) { return esc_html( $value ); } function esc_html__( $value, $domain = '' ) { return esc_html( $value ); } function esc_attr__( $value, $domain = '' ) { return esc_html( $value ); }
function esc_html_e( $value, $domain = '' ) { echo esc_html( $value ); } function esc_attr_e( $value, $domain = '' ) { echo esc_attr( $value ); }
function sanitize_key( $value ) { return preg_replace( '/[^a-z0-9_-]/', '', strtolower( $value ) ); } function sanitize_title( $value ) { return strtolower( trim( preg_replace( '/[^a-zA-Z0-9-]+/', '-', $value ), '-' ) ); } function sanitize_text_field( $value ) { return trim( strip_tags( $value ) ); } function sanitize_textarea_field( $value ) { return trim( strip_tags( $value ) ); }
function wp_unslash( $value ) { return $value; } function wp_strip_all_tags( $value ) { return strip_tags( $value ); } function wp_trim_words( $value, $number, $more = '…' ) { return implode( ' ', array_slice( explode( ' ', $value ), 0, $number ) ); } function strip_shortcodes( $value ) { return $value; }
function absint( $value ) { return abs( (int) $value ); } function number_format_i18n( $value ) { return number_format( $value ); } function wp_json_encode( $value, $flags = 0 ) { return json_encode( $value, $flags ); } function remove_accents( $value ) { return $value; }
function get_option( $key, $default = false ) { return $GLOBALS['options'][ $key ] ?? $default; } function update_option( $key, $value, $autoload = null ) { $GLOBALS['options'][ $key ] = $value; return true; } function delete_option( $key ) { unset( $GLOBALS['options'][ $key ] ); } function add_option( $key, $value, $deprecated = '', $autoload = true ) { if ( isset( $GLOBALS['options'][ $key ] ) ) { return false; } $GLOBALS['options'][ $key ] = $value; return true; }
function wp_generate_uuid4() { static $id = 0; return 'revision-' . ++$id; } function wp_next_scheduled( $hook ) { return $GLOBALS['scheduled'] ?? false; } function wp_schedule_single_event( $time, $hook ) { $GLOBALS['scheduled'] = $time; }
function current_time( $format, $gmt = false ) { return '2026-10-01 12:00:00'; } function wp_date( $format, $timestamp ) { return gmdate( $format, $timestamp ); }
function get_query_var( $key, $default = '' ) { return $GLOBALS['query_vars'][ $key ] ?? $default; } function is_admin() { return false; } function is_404() { return $GLOBALS['conditions']['404'] ?? false; } function is_singular() { return $GLOBALS['conditions']['singular'] ?? false; } function is_front_page() { return $GLOBALS['conditions']['front'] ?? false; } function is_home() { return $GLOBALS['conditions']['home'] ?? false; } function is_search() { return $GLOBALS['conditions']['search'] ?? false; } function is_author() { return false; } function is_date() { return false; } function is_category() { return $GLOBALS['conditions']['term'] ?? false; } function is_tag() { return false; } function is_tax() { return false; }
function get_bloginfo( $name ) { return 'name' === $name ? 'Example Site' : 'A catalogue of videos'; }
function home_url( $path = '/' ) { return 'https://example.test' . $path; } function admin_url( $path = '' ) { return 'https://example.test/wp-admin/' . $path; } function trailingslashit( $value ) { return rtrim( $value, '/' ) . '/'; } function untrailingslashit( $value ) { return rtrim( $value, '/' ); } function user_trailingslashit( $value, $type = '' ) { return trailingslashit( $value ); }
function add_query_arg( $key, $value = '', $url = '' ) { if ( is_array( $key ) ) { $url = $value; $params = $key; } else { $params = array( $key => $value ); } return $url . ( str_contains( $url, '?' ) ? '&' : '?' ) . http_build_query( $params ); }
function majestic_tube_get_option( $group, $key, $default = '' ) { return $GLOBALS['theme_options'][ $key ] ?? $default; }
function majestic_tube_term_seo_supported_taxonomies() { return $GLOBALS['plugin'] ? array() : array( 'category', 'post_tag', 'actors', 'studio', 'series' ); }
function majestic_tube_term_seo_plugin_active() { return $GLOBALS['plugin']; } function majestic_tube_should_output_schema() { return ! $GLOBALS['plugin']; }
function get_post_meta( $id, $key, $single = true ) { return $GLOBALS['post_meta'][ $id ][ $key ] ?? ''; } function update_post_meta( $id, $key, $value ) { $GLOBALS['post_meta'][ $id ][ $key ] = $value; } function delete_post_meta( $id, $key ) { unset( $GLOBALS['post_meta'][ $id ][ $key ] ); }
function get_term_meta( $id, $key, $single = true ) { return $GLOBALS['term_meta'][ $id ][ $key ] ?? ''; } function update_term_meta( $id, $key, $value ) { $GLOBALS['term_meta'][ $id ][ $key ] = $value; }
function get_queried_object_id() { return 99; } function get_queried_object() { return $GLOBALS['queried'] ?? null; } function get_post( $id ) { return (object) array( 'ID' => $id, 'post_title' => 'Video title', 'post_excerpt' => '', 'post_content' => 'Visible video content' ); }
function get_post_type( $id ) { return 'post'; } function wp_is_post_revision( $id ) { return false; } function wp_is_post_autosave( $id ) { return false; } function get_permalink( $id ) { return 'https://example.test/video/'; } function wp_get_canonical_url( $id ) { return get_permalink( $id ); } function esc_url_raw( $value, $protocols = array() ) { return preg_match( '#^https?://#', $value ) ? $value : ''; }
function wp_get_document_title() { return apply_filters( 'pre_get_document_title', 'Default title' ); }
function majestic_tube_term_seo_queried_term() { return is_category() ? get_queried_object() : null; } function majestic_tube_term_seo_description( $term ) { return $GLOBALS['term_meta'][ $term->term_id ]['description'] ?? ''; } function majestic_tube_term_seo_description_placeholder( $term ) { return $term->description ?? ''; } function majestic_tube_term_seo_write( $id, $title, $description ) { $GLOBALS['term_meta'][ $id ] = array( 'title' => $title, 'description' => $description ); }
function current_user_can( $capability, ...$args ) { return $GLOBALS['allowed']; } function wp_verify_nonce( $nonce, $action ) { return 'valid' === $nonce; } function check_admin_referer( $action ) { if ( ! wp_verify_nonce( $_POST['_wpnonce'] ?? '', $action ) ) { throw new RuntimeException( 'nonce denied' ); } }
function wp_nonce_field( $action, $name = '_wpnonce' ) { echo '<input type="hidden" name="' . $name . '" value="valid">'; } function checked( $actual, $expected = true, $echo = true ) { $html = $actual == $expected ? 'checked' : ''; if ( $echo ) { echo $html; } return $html; } function submit_button( $label, $class = 'primary' ) { echo '<button>' . esc_html( $label ) . '</button>'; }
function wp_die( $message ) { throw new RuntimeException( $message ); } function get_current_user_id() { return 1; } function get_transient( $key ) { return $GLOBALS['transients'][ $key ] ?? false; } function set_transient( $key, $value, $ttl ) { $GLOBALS['transients'][ $key ] = $value; } function delete_transient( $key ) { unset( $GLOBALS['transients'][ $key ] ); }
function wp_cache_get( $key, $group ) { return $GLOBALS['cache'][ $group ][ $key ] ?? false; } function wp_cache_set( $key, $value, $group, $ttl = 0 ) { $GLOBALS['cache'][ $group ][ $key ] = $value; }
class WP_Error { public function __construct( public $code, public $message ) {} public function get_error_message() { return $this->message; } } function is_wp_error( $value ) { return $value instanceof WP_Error; }
class WP_Query { public static $queries = array(); public $found_posts = 12; public $is_home = true; public $is_archive = false; public $is_singular = true; public $is_tax = false; public $is_category = false; public $is_tag = false; public $args = array(); public function __construct( $args = array() ) { $this->args = $args; self::$queries[] = $args; if ( ! empty( $args['no_found_rows'] ) ) { $this->found_posts = 0; } } public function is_main_query() { return true; } public function set( $key, $value ) { $this->args[ $key ] = $value; } }
abstract class WP_Sitemaps_Provider { protected $name = ''; protected $object_type = ''; abstract public function get_url_list( $page_num, $object_subtype = '' ); abstract public function get_max_num_pages( $object_subtype = '' ); }
function wp_sitemaps_get_max_urls( $type ) { return 2; } function wp_register_sitemap_provider( $key, $provider ) { $GLOBALS['provider'] = $provider; }
$terms = array();
foreach ( array( array( 1, 'actors', 'alex', 'Alex' ), array( 2, 'category', 'comedy', 'Comedy' ), array( 3, 'actors', 'jordan', 'Jordan' ), array( 4, 'post_tag', 'classic', 'Classic' ), array( 5, 'studio', 'studio', 'Studio' ) ) as $data ) { $terms[ $data[0] ] = (object) array( 'term_id' => $data[0], 'term_taxonomy_id' => $data[0], 'taxonomy' => $data[1], 'slug' => $data[2], 'name' => $data[3], 'description' => 'Term introduction' ); }
$GLOBALS['terms'] = $terms;
function get_term( $id ) { return $GLOBALS['terms'][ $id ] ?? null; } function get_term_by( $field, $value, $taxonomy ) { foreach ( $GLOBALS['terms'] as $term ) { if ( $term->taxonomy === $taxonomy && $term->$field === $value ) { return $term; } } return false; } function get_term_link( $term ) { return home_url( '/' . $term->taxonomy . '/' . $term->slug . '/' ); } function get_terms( $args ) { return array_values( array_filter( $GLOBALS['terms'], function ( $term ) use ( $args ) { return empty( $args['include'] ) || in_array( $term->term_id, $args['include'] ); } ) ); } function get_taxonomy( $taxonomy ) { return (object) array( 'cap' => (object) array( 'manage_terms' => 'manage_categories' ) ); }
class TestDB {
 public $prefix = 'wp_'; public $posts = 'wp_posts'; public $term_relationships = 'wp_term_relationships'; public $term_taxonomy = 'wp_term_taxonomy'; public $postmeta = 'wp_postmeta'; public $last_error = ''; public $sql = array(); public $fail_insert = false; public $revision_change = false;
 function prepare( $sql, ...$args ) { if ( isset( $args[0] ) && is_array( $args[0] ) ) { $args = $args[0]; } foreach ( $args as $value ) { $sql = preg_replace_callback( '/%[ds]/', function ( $m ) use ( $value ) { return '%d' === $m[0] ? (string) (int) $value : "'" . str_replace( "'", "''", $value ) . "'"; }, $sql, 1 ); } return $sql; }
 function get_results( $sql, $output = null ) { $this->sql[] = $sql; if ( str_contains( $sql, 'SELECT term_id FROM' ) ) { return array( (object) array( 'term_id' => 1 ) ); } if ( str_contains( $sql, 'AS secondary' ) ) { return array( array( 'secondary' => str_contains( $sql, "'actors'" ) ? 3 : 2, 'count' => 12 ) ); } if ( str_contains( $sql, 'SELECT * FROM' ) ) { return array( array( 'facet_type' => 'actor_category', 'url' => home_url( '/actor/alex/comedy/' ), 'term_id' => 1, 'term2_id' => 2, 'band' => '', 'video_count' => 12, 'label' => 'Alex in Comedy' ) ); } return array(); }
 function get_var( $sql ) { $this->sql[] = $sql; return 12; } function get_row( $sql, $output = null ) { $this->sql[] = $sql; return array( 'total' => 12, 'runtime' => 1200, 'hd' => 2, 'first' => '2024-01-01', 'last' => '2026-01-01' ); }
 function replace( $table, $row ) { if ( $this->revision_change ) { update_option( 'majestic_tube_seo_data_revision', 'changed-mid-build' ); } return $this->fail_insert ? false : 1; } function query( $sql ) { $this->sql[] = $sql; return 1; }
}
$GLOBALS['wpdb'] = new TestDB();
foreach ( array( 'pseo.php', 'pseo-stats.php', 'pseo-meta.php', 'pseo-render.php', 'pseo-sitemap.php', 'seo.php', 'seo-index.php', 'seo-admin.php' ) as $file ) { require dirname( __DIR__ ) . '/inc/' . $file; }
$passed = 0;
function check( $label, $actual, $expected = true ) { global $passed; if ( $actual !== $expected ) { throw new RuntimeException( $label . ': ' . var_export( $actual, true ) . ' != ' . var_export( $expected, true ) ); } $passed++; echo "ok $label\n"; }
foreach ( majestic_tube_collection_defaults() as $type => $default ) {
 $config = majestic_tube_collection_validate( $type, $default ); check( "$type template valid", ! is_wp_error( $config ) );
 $facet = majestic_tube_seo_example( $type ); check( "$type tokens resolve", ! str_contains( majestic_tube_collection_text( $config['title'], $facet ), '{' ) );
 $bad = $default; $bad['title'] = '{untrusted.php}'; check( "$type unknown token rejected", is_wp_error( majestic_tube_collection_validate( $type, $bad ) ) );
 $bad['title'] = '{actor.name'; check( "$type unmatched brace rejected", is_wp_error( majestic_tube_collection_validate( $type, $bad ) ) );
}
check( 'unknown collection rejected', is_wp_error( majestic_tube_collection_validate( 'invalid', array() ) ) );
check( 'pair URL deduplicated', majestic_tube_facet_url( 'actor_actor', $terms[3], $terms[1] ), home_url( '/actor/alex/with/jordan/' ) );
$args = majestic_tube_facet_query( 'actor_category', $terms[1], $terms[2] ); check( 'actor/category second taxonomy', $args['tax_query'][1]['taxonomy'], 'category' ); check( 'exact category membership', $args['tax_query'][1]['include_children'], false );
check( 'studio query uses studio', majestic_tube_facet_query( 'studio', $terms[5] )['tax_query'][0]['taxonomy'], 'studio' );
check( 'open duration bound scalar', majestic_tube_facet_query( 'actor_length', $terms[1], null, 'longest' )['meta_query'][0]['value'], 3600 );
check( 'exact count available', majestic_tube_facet_count( 'actor_category', $terms[1], $terms[2] ), 12 );
check( 'count query totals enabled', end( WP_Query::$queries )['no_found_rows'], false );
$count = count( WP_Query::$queries ); majestic_tube_facet_count( 'actor_category', $terms[1], $terms[2] ); check( 'count request memoized', count( WP_Query::$queries ), $count );
$GLOBALS['query_vars'] = array( 'mt_facet' => 'actor_category', 'mt_facet_taxonomy' => 'actors', 'mt_facet_term' => 'alex', 'mt_facet_term2' => 'comedy', 'paged' => 2 );
check( 'resolver finds valid facet', majestic_tube_current_facet()['count'], 12 );
check( 'core cannot redirect virtual URL to unrelated post', apply_filters( 'redirect_canonical', home_url( '/wrong/' ) ), false );
$q = new WP_Query(); majestic_tube_facet_pre_get_posts( $q ); check( 'grid same taxonomy', $q->args['tax_query'], $args['tax_query'] ); check( 'facet is archive', $q->is_singular, false );
ob_start(); majestic_tube_facet_meta_description(); majestic_tube_facet_canonical(); majestic_tube_facet_schema(); $head = ob_get_clean();
check( 'archive description rendered', substr_count( $head, 'name="description"' ), 1 ); check( 'page two self canonical', str_contains( $head, '/actor/alex/comedy/page/2/' ) ); check( 'archive schema rendered', str_contains( $head, 'CollectionPage' ) );
check( 'pagination not universally noindex', isset( majestic_tube_facet_robots( array() )['noindex'] ), false );
$GLOBALS['options']['majestic_tube_collections'] = array( 'actor_category' => array( 'enabled' => false ) );
check( 'disabled collection gate', majestic_tube_facet_indexable( 'actor_category', 12, $terms[1], $terms[2] ), false );
$GLOBALS['query_vars'] = array( 'mt_browse' => 1, 'mt_facet' => 'actor-category', 'mt_facet_band' => 'a', 'paged' => 2 );
ob_start(); majestic_tube_facet_canonical(); $canonical = ob_get_clean(); check( 'browse group+letter canonical', str_contains( $canonical, '/browse/actor-category/a/page/2/' ) ); check( 'browse noindex', majestic_tube_facet_robots( array() )['noindex'] );
$GLOBALS['query_vars'] = array(); $GLOBALS['conditions'] = array( 'term' => true ); $GLOBALS['queried'] = $terms[2]; $GLOBALS['term_meta'][2]['description'] = 'Custom term description';
ob_start(); majestic_tube_seo_head(); $head = ob_get_clean(); check( 'term head description', str_contains( $head, 'Custom term description' ) );
$GLOBALS['conditions'] = array( 'singular' => true ); $GLOBALS['post_meta'][99] = array( 'majestic_tube_seo_title' => 'My search title', 'majestic_tube_seo_description' => 'My snippet', 'majestic_tube_seo_noindex' => '1' );
check( 'post title override', majestic_tube_seo_title( '' ), 'My search title' ); check( 'post description override', majestic_tube_seo_description(), 'My snippet' ); check( 'post noindex', majestic_tube_seo_robots( array() )['noindex'] );
$tags = majestic_tube_seo_social( array( 'og:title' => 'old', 'og:description' => 'old', 'og:url' => 'old' ) ); check( 'social title follows search', $tags['og:title'], 'My search title' ); check( 'social canonical not homepage', $tags['og:url'], get_permalink( 99 ) );
$GLOBALS['conditions'] = array( 'front' => true ); $GLOBALS['options']['majestic_tube_search_settings'] = array( 'home_title' => 'Homepage search title', 'home_description' => 'Homepage snippet' );
check( 'homepage search title', majestic_tube_seo_title( '' ), 'Homepage search title' ); check( 'homepage snippet', majestic_tube_seo_description(), 'Homepage snippet' );
$GLOBALS['plugin'] = true; ob_start(); majestic_tube_seo_head(); majestic_tube_facet_meta_description(); $head = ob_get_clean(); check( 'plugin stand down', $head, '' ); check( 'plugin title unchanged', majestic_tube_seo_title( 'External' ), 'External' ); $GLOBALS['plugin'] = false;
check( 'correct sitemap lifecycle hook', isset( $GLOBALS['hooks']['wp_sitemaps_init'] ) ); check( 'no nonexistent sitemap hook', isset( $GLOBALS['hooks']['init_sitemaps'] ), false );
majestic_tube_register_facet_sitemap(); check( 'provider registered as instance', $GLOBALS['provider'] instanceof WP_Sitemaps_Provider );
$GLOBALS['options']['majestic_tube_seo_index_schema'] = '1'; $GLOBALS['options']['majestic_tube_seo_index_active'] = array( 'generation' => 'old', 'revision' => 'old-revision' ); $GLOBALS['options']['majestic_tube_seo_data_revision'] = 'new';
$where = majestic_tube_seo_index_where( 'generated' ); check( 'sitemap excludes studio', ! str_contains( $where, "'studio'" ) ); check( 'disabled collection excluded immediately', ! str_contains( $where, "'actor_category'" ) );
majestic_tube_seo_index_rows( 'actor_actor', 5000, -1 ); check( 'bounded reads', str_contains( end( $GLOBALS['wpdb']->sql ), 'LIMIT 2000 OFFSET 0' ) );
$GLOBALS['options']['majestic_tube_collections'] = array(); $GLOBALS['wpdb']->fail_insert = true;
majestic_tube_seo_index_tick(); check( 'failed build preserves active', get_option( 'majestic_tube_seo_index_active' )['generation'], 'old' ); check( 'failed build reports error', (bool) get_option( 'majestic_tube_seo_index_error' ) ); check( 'lock released', get_option( 'majestic_tube_seo_index_lock' ), false );
majestic_tube_seo_index_tick(); check( 'errored build waits for explicit retry', get_option( 'majestic_tube_seo_index_active' )['generation'], 'old' );
$GLOBALS['wpdb']->fail_insert = false; delete_option( 'majestic_tube_seo_index_error' ); $GLOBALS['wpdb']->revision_change = true; majestic_tube_seo_index_tick(); check( 'changed data never promotes partial build', get_option( 'majestic_tube_seo_index_active' )['generation'], 'old' );
$GLOBALS['wpdb']->revision_change = false; majestic_tube_seo_index_tick(); check( 'complete build promoted', get_option( 'majestic_tube_seo_index_active' )['generation'] !== 'old' );
check( 'job cleared on completion', get_option( 'majestic_tube_seo_index_job' ), false );
$GLOBALS['query_vars'] = array(); $GLOBALS['conditions'] = array(); $_SERVER['REQUEST_METHOD'] = 'POST'; $_POST = array( '_wpnonce' => 'valid', 'seo_action' => 'preview', 'config' => majestic_tube_collection_defaults()['actor_category'] );
$before = get_option( 'majestic_tube_collections' ); $result = majestic_tube_seo_admin_submission( 'templates', 'actor_category' ); check( 'preview validates', is_array( $result['preview'] ) ); check( 'preview does not save', get_option( 'majestic_tube_collections' ), $before );
$_POST['seo_action'] = 'publish'; $result = majestic_tube_seo_admin_submission( 'templates', 'actor_category' ); check( 'publish requires confirmation', (bool) $result['error'] );
$_POST['confirm'] = '1'; $result = majestic_tube_seo_admin_submission( 'templates', 'actor_category' ); check( 'confirmed save', (bool) $result['notice'] ); check( 'revision history saved', count( get_option( 'majestic_tube_collection_history' )['actor_category'] ), 1 );
$_POST['_wpnonce'] = 'bad'; $denied = false; try { majestic_tube_seo_admin_submission( 'templates', 'actor_category' ); } catch ( RuntimeException $e ) { $denied = true; } check( 'bad nonce denied', $denied );
$GLOBALS['allowed'] = false; check( 'unauthorized mutation blocked', majestic_tube_seo_admin_submission( 'templates', 'actor_category' )['notice'], '' ); $GLOBALS['allowed'] = true;
$_SERVER['REQUEST_METHOD'] = 'GET'; $_POST = array();
foreach ( array( 'overview', 'collections', 'templates', 'data', 'settings' ) as $tab ) { $_GET = array( 'tab' => $tab ); ob_start(); majestic_tube_seo_admin_page(); $html = ob_get_clean(); check( "$tab admin renders", str_contains( $html, 'mt-seo-workspace' ) ); }
$_GET = array( 'tab' => 'templates', 'collection' => 'actor_category' ); ob_start(); majestic_tube_seo_admin_page(); $html = ob_get_clean(); check( 'template editor renders', str_contains( $html, 'Preview changes' ) ); check( 'template previews escaped', ! str_contains( $html, 'value="<script' ) );
$source = file_get_contents( dirname( __DIR__ ) . '/index.php' ); check( 'homepage no forced repetition', ! str_contains( $source, 'homepage-seo-footer' ) );
$GLOBALS['query_vars'] = array( 'mt_facet' => 'actor_category', 'mt_facet_taxonomy' => 'actors', 'mt_facet_term' => 'alex', 'mt_facet_term2' => 'missing' ); check( 'missing secondary never resolves', majestic_tube_current_facet(), null );
$GLOBALS['query_vars'] = array( 'mt_facet' => 'actor_actor', 'mt_facet_taxonomy' => 'actors', 'mt_facet_term' => 'alex', 'mt_facet_term2' => 'alex' ); check( 'self pair rejected', majestic_tube_current_facet(), null );
$GLOBALS['query_vars'] = array( 'mt_facet' => 'actor_length', 'mt_facet_taxonomy' => 'actors', 'mt_facet_term' => 'alex', 'mt_facet_band' => 'invalid' ); check( 'unknown duration band rejected', majestic_tube_current_facet(), null );
$GLOBALS['query_vars'] = array();
$GLOBALS['conditions'] = array( 'singular' => true ); $_POST = array( 'majestic_tube_search_nonce' => 'valid', 'majestic_tube_seo_title' => '<b>Clean title</b>', 'majestic_tube_seo_canonical' => get_permalink( 99 ), 'majestic_tube_seo_noindex' => 'garbage' ); majestic_tube_seo_save_post( 99 );
check( 'post save sanitizes title', get_post_meta( 99, 'majestic_tube_seo_title', true ), 'Clean title' ); check( 'self canonical override cleared', get_post_meta( 99, 'majestic_tube_seo_canonical', true ), '' ); check( 'noindex normalized', get_post_meta( 99, 'majestic_tube_seo_noindex', true ), '' );
$_POST = array(); majestic_tube_seo_save_post( 99 ); check( 'quick edit preserves override', get_post_meta( 99, 'majestic_tube_seo_title', true ), 'Clean title' );
$too_long = majestic_tube_collection_defaults()['actor_category']; $too_long['title'] = str_repeat( 'x', 2001 ); check( 'oversized template rejected', is_wp_error( majestic_tube_collection_validate( 'actor_category', $too_long ) ) );
$filtered = majestic_tube_seo_sitemap_args( array( 'meta_query' => array( 'relation' => 'OR', array( 'key' => 'existing' ) ) ), 'post' ); check( 'sitemap exclusions cannot be OR bypassed', $filtered['meta_query']['relation'], 'AND' );
check( 'wp_meta not used as filter', ! str_contains( file_get_contents( dirname( __DIR__ ) . '/inc/term-seo.php' ), "add_filter( 'wp_meta'" ) );
function parse_csv_test( $text ) { $stream = fopen( 'php://temp', 'r+' ); fwrite( $stream, $text ); rewind( $stream ); try { return majestic_tube_seo_csv_read( $stream ); } finally { fclose( $stream ); } }
$rows = parse_csv_test( "taxonomy,slug,title,description\ncategory,comedy,New title,New description\n" ); check( 'CSV validates existing term', $rows[0]['slug'], 'comedy' );
$rows = parse_csv_test( "taxonomy,slug,title,description\ncategory,comedy,,\n" ); check( 'CSV blank fields are explicit clears', $rows[0]['description'], '' );
foreach ( array( 'bad headers' => "name,title\ncomedy,test\n", 'unknown term' => "taxonomy,slug,title,description\ncategory,missing,test,test\n", 'duplicate term' => "taxonomy,slug,title,description\ncategory,comedy,test,test\ncategory,comedy,test,test\n" ) as $label => $csv ) { $rejected = false; try { parse_csv_test( $csv ); } catch ( RuntimeException $e ) { $rejected = true; } check( 'CSV rejects ' . $label, $rejected ); }
$GLOBALS['plugin'] = true; $rejected = false; try { parse_csv_test( "taxonomy,slug,title,description\ncategory,comedy,test,test\n" ); } catch ( RuntimeException $e ) { $rejected = true; } check( 'CSV cannot bypass external metadata owner', $rejected ); $GLOBALS['plugin'] = false;
if ( '--render' === ( $argv[1] ?? '' ) ) {
 $saved = $GLOBALS['options']; $GLOBALS['conditions'] = array(); $GLOBALS['query_vars'] = array(); $_POST = array(); $_SERVER['REQUEST_METHOD'] = 'GET';
 $css = file_get_contents( dirname( __DIR__ ) . '/assets/css/seo-admin.css' );
 $js = file_get_contents( dirname( __DIR__ ) . '/assets/js/seo-admin.js' );
 $GLOBALS['options']['majestic_tube_seo_index_schema'] = '0';
 $_GET = array( 'tab' => 'templates', 'collection' => 'actor_category' );
 ob_start(); majestic_tube_seo_admin_page(); $markup = ob_get_clean();
 $base = 'body{background:#f0f0f1;color:#1d2327;font:14px system-ui;margin:24px}a{color:#2271b1}.nav-tab-wrapper{display:flex;gap:12px;border-bottom:1px solid #ccd0d4;padding:12px 0}.nav-tab{padding:10px;text-decoration:none}.nav-tab-active{background:white}textarea{box-sizing:border-box;padding:10px;border:1px solid #8c8f94;border-radius:3px;font:14px system-ui;width:100%}.button,button{padding:8px 12px;border:1px solid #2271b1;border-radius:3px;background:white;color:#2271b1;cursor:pointer}.button-primary{background:#2271b1;color:white}.large-text{width:100%}.description{color:#646970}.widefat{width:100%;text-align:left}';
 file_put_contents( dirname( __DIR__ ) . '/tests/seo-preview.html', '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Theme-native SEO editor preview</title><style>' . $base . $css . '</style></head><body><p>Static test-rendered preview—not a running WordPress admin.</p>' . $markup . '<script>' . $js . '</script></body></html>' );
 echo "Rendered tests/seo-preview.html\n";
}
echo "$passed checks passed\n";
